const baseIconUrl = "https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_";

export const FileIconTypes : Record<string, string> = {
    "file": "",
    "access": "accdb, accdt, mdb, accda, accdc, accde, accdp, accdr, accdu, ade, adp, laccdb, ldb, mam, maq, mdw",
    "access2": "accdb, accdt, mdb, accda, accdc, accde, accdp, accdr, accdu, ade, adp, laccdb, ldb, mam, maq, mdw",
    "actionscript": "actionscript",
    "actionscript2": "actionscript",
    "ada": "ada",
    "advpl": "advpl",
    "ai": "ai",
    "ai2": "ai",
    "al": "al",
    "allcontributors": ".all-contributorsrc",
    "affinitydesigner": "afdesign, affinitydesigner",
    "affinityphoto": "afphoto, affinityphoto",
    "affinitypublisher": "afpub, affinitypublisher",
    "appscript": "gs",
    "fitbit": "fba",
    "angular": ".angular-cli.json, angular-cli.json, angular.json, .angular.json",
    "ng_component_dart": "component.dart",
    "ng_component_ts": "component.ts",
    "ng_component_js": "component.js",
    "ng_controller_ts": "controller.ts",
    "ng_controller_js": "controller.js",
    "ng_directive_dart": "directive.dart",
    "ng_directive_ts": "directive.ts",
    "ng_directive_js": "directive.js",
    "ng_guard_dart": "guard.dart",
    "ng_guard_ts": "guard.ts",
    "ng_guard_js": "guard.js",
    "ng_module_dart": "module.dart",
    "ng_module_ts": "module.ts",
    "ng_module_js": "module.js",
    "ng_pipe_dart": "pipe.dart",
    "ng_pipe_ts": "pipe.ts",
    "ng_pipe_js": "pipe.js",
    "ng_routing_dart": "app-routing.module.dart",
    "ng_routing_ts": "app-routing.module.ts",
    "ng_routing_js": "app-routing.module.js",
    "ng_smart_component_dart": "page.dart, container.dart",
    "ng_smart_component_ts": "page.ts, container.ts",
    "ng_smart_component_js": "page.js, container.js",
    "ng_service_dart": "service.dart",
    "ng_service_ts": "service.ts",
    "ng_service_js": "service.js",
    "ng_interceptor_dart": "interceptor.dart",
    "ng_interceptor_ts": "interceptor.ts",
    "ng_interceptor_js": "interceptor.js",
    "ng_component_ts2": "component.ts",
    "ng_component_js2": "component.js",
    "ng_directive_ts2": "directive.ts",
    "ng_directive_js2": "directive.js",
    "ng_module_ts2": "module.ts",
    "ng_module_js2": "module.js",
    "ng_pipe_ts2": "pipe.ts",
    "ng_pipe_js2": "pipe.js",
    "ng_routing_ts2": "app-routing.module.ts",
    "ng_routing_js2": "app-routing.module.js",
    "ng_smart_component_ts2": "page.ts, container.ts",
    "ng_smart_component_js2": "page.js, container.js",
    "ng_service_ts2": "service.ts",
    "ng_service_js2": "service.js",
    "ng_tailwind": "ng-tailwind.js",
    "affectscript": "affectscript",
    "ansible": "ansible",
    "antlr": "antlr",
    "anyscript": "anyscript",
    "apache": "apacheconf",
    "apex": "apex",
    "apib": "apiblueprint",
    "api_extractor": "api-extractor.json, api-extractor-base.json",
    "apl": "apl",
    "applescript": "applescript",
    "appsemble": ".appsemblerc.yaml, app-definition.yaml",
    "appveyor": "appveyor.yml, .appveyor.yml",
    "arduino": "ino, pde",
    "asciidoc": "asciidoc",
    "asp": "asp, asp (html)",
    "aspx": "aspx, ascx",
    "assembly": "arm, asm",
    "astro": "astro",
    "astroconfig": "astro.config.js, astro.config.cjs, astro.config.mjs, astro.config.ts",
    "ats": "ats",
    "audio": "aac, act, aiff, amr, ape, au, dct, dss, dvf, flac, gsm, iklax, ivs, m4a, m4b, m4p, mmf, mogg, mp3, mpc, msv, oga, ogg, opus, ra, raw, tta, vox, wav, wma",
    "aurelia": "aurelia.json",
    "autohotkey": "ahk",
    "autoit": "autoit",
    "avif": "avif",
    "avro": "avro",
    "awk": "awk",
    "aws": "",
    "azure": "azcli",
    "azurepipelines": "azure-pipelines.yml, .vsts-ci.yml, azure-pipelines",
    "babel": ".babelrc, .babelignore, .babelrc.js, .babelrc.cjs, .babelrc.mjs, .babelrc.json, babel.config.js, babel.config.cjs, babel.config.mjs, babel.config.json",
    "babel2": ".babelrc, .babelignore, .babelrc.js, .babelrc.cjs, .babelrc.mjs, .babelrc.json, babel.config.js, babel.config.cjs, babel.config.mjs, babel.config.json",
    "ballerina": "ballerina",
    "bat": "bat",
    "bats": "bats",
    "bazaar": ".bzrignore",
    "bazel": "BUILD.bazel, .bazelrc, bazel.rc, bazel.bazelrc, bazel, starlark",
    "befunge": "befunge, befunge98",
    "bicep": "bicep",
    "biml": "biml",
    "binary": "a, app, bin, cmo, cmx, cma, cmxa, cmi, dll, exe, hl, ilk, lib, n, ndll, o, obj, pyc, pyd, pyo, pdb, scpt, scptd, so",
    "bithound": ".bithoundrc",
    "bitbucketpipeline": "bitbucket-pipelines.yml",
    "blade": "blade, laravel-blade",
    "blitzbasic": "bb, blitzbasic",
    "bolt": "bolt",
    "bosque": "bosque",
    "bower": ".bowerrc, bower.json",
    "browserslist": ".browserslistrc, browserslist",
    "buckbuild": ".buckconfig",
    "bundler": "gemfile, gemfile.lock",
    "c": "c",
    "c2": "c",
    "c3": "c",
    "c_al": "c-al",
    "cabal": "cabal",
    "caddy": "caddyfile",
    "cake": "cake",
    "cakephp": "",
    "capacitor": "capacitor.config.json",
    "cargo": "cargo.toml, cargo.lock",
    "casc": "casc",
    "cddl": "cddl",
    "cert": "csr, crt, cer, der, pfx, p12, p7b, p7r, src, crl, sst, stl",
    "ceylon": "ceylon",
    "cf": "lucee, cfml, lang-cfml",
    "cf2": "lucee, cfml, lang-cfml",
    "cfc": "cfc",
    "cfc2": "cfc",
    "cfm": "cfmhtml",
    "cfm2": "cfmhtml",
    "cheader": "h",
    "chef": "chefignore, berksfile, berksfile.lock, policyfile.rb, policyfile.lock.json",
    "class": "class",
    "circleci": "circle.yml",
    "clojure": "cjm, cljc, clojure",
    "clojurescript": "cljs, clojurescript",
    "cloudfoundry": ".cfignore, manifest-yaml",
    "cmake": "cmake, cmake-cache",
    "cobol": "cobol",
    "codeql": "ql",
    "codeowners": "codeowners",
    "codacy": ".codacy.yml, .codacy.yaml",
    "codeclimate": ".codeclimate.yml",
    "codecov": "codecov.yml, .codecov.yml",
    "codekit": "config.codekit, config.codekit2, config.codekit3, .config.codekit, .config.codekit2, .config.codekit3",
    "coffeelint": "coffeelint.json, .coffeelintignore",
    "coffeescript": "coffeescript",
    "conan": "conanfile.txt, conanfile.py",
    "conda": ".condarc",
    "config": ".tool-versions",
    "commitizen": ".czrc, .cz.json",
    "commitlint": "commitlint.config.js, commitlint.config.cjs, commitlint.config.ts, .commitlintrc.json, .commitlintrc.yaml, .commitlintrc.yml, .commitlintrc.js, .commitlintrc.cjs, .commitlintrc.ts",
    "compass": "",
    "composer": "composer.json, composer.lock",
    "chef_cookbook": "cookbook",
    "confluence": "confluence",
    "coveralls": ".coveralls.yml",
    "cpp": "cpp",
    "cpp2": "cpp",
    "cpp3": "cpp",
    "cppheader": "hpp, hh, hxx, h++",
    "crowdin": "crowdin.yml",
    "crystal": "crystal",
    "csharp": "csx, csharp",
    "csharp2": "csx, csharp",
    "csproj": "csproj",
    "css": "css",
    "csscomb": ".csscomb.json",
    "csslint": ".csslintrc",
    "cssmap": "css.map",
    "cucumber": "feature",
    "cuda": "cuda, cuda-cpp",
    "cython": "cython",
    "cypress": "cypress.json, cypress.env.json, cypress.config.js, cypress.config.ts, cypress.config.cjs, cypress.config.mjs",
    "cypress_spec": "cy.js, cy.mjs, cy.cjs, cy.coffee, cy.ts, cy.tsx, cy.jsx",
    "cvs": ".cvsignore",
    "dal": "dal",
    "darcs": ".boringignore",
    "dartlang": "dart",
    "dartlang_generated": "g.dart, freezed.dart",
    "dartlang_ignore": ".pubignore",
    "db": "db",
    "dependabot": "dependabot.yml",
    "dependencies": "dependencies.yml",
    "delphi": "pascal, objectpascal",
    "devcontainer": "devcontainer.json, .devcontainer.json",
    "dhall": "dhall",
    "django": "djt, django-html, django-txt",
    "dlang": "d, dscript, dml, diet",
    "diff": "diff",
    "docker": ".dockerignore, compose.yaml, compose.yml, docker-compose.yaml, docker-compose.yml, docker-compose.ci-build.yaml, docker-compose.ci-build.yml, docker-compose.override.yaml, docker-compose.override.yml, docker-compose.vs.debug.yaml, docker-compose.vs.debug.yml, docker-compose.vs.release.yaml, docker-compose.vs.release.yml, docker-cloud.yaml, docker-cloud.yml, dockerfile",
    "docker2": ".dockerignore, compose.yaml, compose.yml, docker-compose.yaml, docker-compose.yml, docker-compose.ci-build.yaml, docker-compose.ci-build.yml, docker-compose.override.yaml, docker-compose.override.yml, docker-compose.vs.debug.yaml, docker-compose.vs.debug.yml, docker-compose.vs.release.yaml, docker-compose.vs.release.yml, docker-cloud.yaml, docker-cloud.yml, dockerfile",
    "dockertest": "docker-compose.test.yml",
    "dockertest2": "docker-compose.test.yml",
    "docpad": "eco",
    "docz": ".doczrc, docz.js, docz.json, .docz.js, .docz.json, doczrc.js, doczrc.json, docz.config.js, docz.config.json",
    "dojo": ".dojorc",
    "doxygen": "doxygen",
    "drawio": "drawio, dio .drawio.png, .drawio.svg, .dio.png, .dio.svg",
    "drone": ".drone.yml, .drone.yml.sig",
    "drools": "drools",
    "dotjs": "dotjs",
    "dustjs": "dustjs",
    "dvc": ".dvc",
    "dylan": "dylan, dylan-lid",
    "editorconfig": ".editorconfig",
    "earthly": ".earthlyignore, Earthfile, earthfile",
    "edge": "edge",
    "edge2": "edge",
    "eex": "eex, html-eex",
    "ejs": "ejs",
    "elastic": "es",
    "elasticbeanstalk": "",
    "elixir": "elixir",
    "elm": "elm-package.json, elm",
    "elm2": "elm-package.json, elm",
    "emacs": "el, elc",
    "ember": ".ember-cli",
    "ensime": "ensime",
    "eps": "eps",
    "erb": "erb, html.erb",
    "erlang": "emakefile, .emakerfile, erlang",
    "erlang2": "emakefile, .emakerfile, erlang",
    "eslint": ".eslintrc, .eslintignore, .eslintcache, .eslintrc.js, .eslintrc.mjs, .eslintrc.cjs, .eslintrc.json, .eslintrc.yaml, .eslintrc.yml",
    "eslint2": ".eslintrc, .eslintignore, .eslintcache, .eslintrc.js, .eslintrc.mjs, .eslintrc.cjs, .eslintrc.json, .eslintrc.yaml, .eslintrc.yml",
    "excel": "xls, xlsx, xlsm, ods, fods, xlsb",
    "excel2": "xls, xlsx, xlsm, ods, fods, xlsb",
    "expo": "app.json, app.config.js, app.config.json, app.config.json5",
    "falcon": "falcon",
    "fauna": ".faunarc, fql",
    "favicon": "favicon.ico",
    "fbx": "fbx",
    "firebase": ".firebaserc",
    "firebasehosting": "firebase.json",
    "firestore": "firestore.rules, firestore.indexes.json",
    "fla": "fla",
    "flareact": "flareact.config.js",
    "flash": "swf, swc",
    "floobits": ".flooignore",
    "flow": ".flowconfig",
    "flutter": ".flutter-plugins, .metadata",
    "flutter_package": "pubspec.lock, pubspec.yaml, .packages",
    "font": "woff, woff2, ttf, otf, eot, pfa, pfb, sfd",
    "formkit": "formkit.config.js, formkit.config.mjs, formkit.config.cjs, formkit.config.ts",
    "fortran": "fortran, fortran-modern, FortranFreeForm, FortranFixedForm, fortran_fixed-form",
    "fossa": ".fossaignore",
    "fossil": "ignore-glob",
    "fsharp": "fsharp",
    "fsproj": "fsproj",
    "freemarker": "ftl",
    "fthtml": "fthtml",
    "funding": "funding.yml",
    "fusebox": "fuse.js",
    "galen": "galen",
    "galen2": "galen",
    "git": ".gitattributes, .gitconfig, .gitignore, .gitmodules, .gitkeep, .mailmap, .issuetracker, git-commit, git-rebase, ignore",
    "gamemaker": "gmx, gml-gms",
    "gamemaker2": "yy, yyp, gml-gms2",
    "gamemaker81": "gml-gm81",
    "gatsby": "gatsby-config.js, gatsby-config.ts, gatsby-node.js, gatsby-node.ts",
    "gcode": "gcode",
    "genstat": "genstat",
    "gitlab": ".gitlab-ci.yml",
    "gitpod": ".gitpod.yaml, .gitpod.yml, gitpod.yaml, gitpod.yml",
    "glide": "glide.yml",
    "glitter": ".glitterrc",
    "glsl": "glsl",
    "glyphs": "glyphs",
    "gnuplot": "gnuplot",
    "go": "go",
    "go_package": "go.sum, go.mod",
    "goctl": "goctl",
    "godot": "gdscript",
    "gradle": "gradle",
    "gradle2": "gradle",
    "graphql": ".gqlconfig, graphql",
    "graphql_config": ".graphqlconfig, .graphqlconfig.yml, .graphqlconfig.yaml",
    "graphviz": "dot",
    "greenkeeper": "greenkeeper.json",
    "gridsome": "gridsome.config.js, gridsome.config.ts, gridsome.server.js, gridsome.server.ts, gridsome.client.js, gridsome.client.ts",
    "groovy": "groovy",
    "groovy2": "groovy",
    "grunt": "gruntfile.js, gruntfile.coffee, gruntfile.ts, gruntfile.babel.js, gruntfile.babel.coffee, gruntfile.babel.ts",
    "gulp": "gulpfile.js, gulpfile.coffee, gulpfile.ts, gulpfile.mjs, gulpfile.esm.js, gulpfile.esm.coffee, gulpfile.esm.ts, gulpfile.esm.mjs, gulpfile.babel.js, gulpfile.babel.coffee, gulpfile.babel.ts, gulpfile.babel.mjs",
    "haml": "haml",
    "handlebars": "handlebars",
    "handlebars2": "handlebars",
    "harbour": "harbour",
    "hardhat": "hardhat.config.js, hardhat.config.ts",
    "haskell": "haskell, literate haskell",
    "haskell2": "haskell, literate haskell",
    "haxe": "haxelib.json, haxe, hxml, Haxe AST dump",
    "haxecheckstyle": "checkstyle.json",
    "haxedevelop": "hxproj",
    "helix": ".p4ignore",
    "helm": "chart.lock, chart.yaml, helm",
    "hjson": "hjson",
    "hlsl": "hlsl",
    "homeassistant": "home-assistant",
    "horusec": "horusec-config.json",
    "host": "hosts",
    "html": "html",
    "htmlhint": ".htmlhintrc",
    "http": "http",
    "hunspell": "hunspell.aff, hunspell.dic",
    "husky": ".huskyrc, husky.config.js, .huskyrc.js, .huskyrc.json, .huskyrc.yaml, .huskyrc.yml",
    "hy": "hy",
    "hygen": "ejs.t",
    "hypr": "hypr",
    "icl": "icl",
    "idris": "idr, lidr",
    "idrisbin": "ibc",
    "idrispkg": "ipkg",
    "image": "jpeg, jpg, gif, png, bmp, tiff, ico, webp",
    "imba": "imba, imba2, imba",
    "inc": "inc, include",
    "infopath": "infopathxml, xsn, xsf, xtp2",
    "informix": "4GL",
    "ini": "ini",
    "ink": "ink",
    "innosetup": "innosetup",
    "ionic": "ionic.project, ionic.config.json",
    "jake": "jakefile, jakefile.js",
    "janet": "janet",
    "jar": "jar",
    "jasmine": "jasmine.json",
    "java": "java",
    "jbuilder": "jbuilder",
    "jest": "jest.config.json, jest.config.base.json, jest.config.common.json, jest.config.ts, jest.config.base.ts, jest.config.common.ts, jest.json, .jestrc, .jestrc.js, .jestrc.json, jest.config.js, jest.config.cjs, jest.config.mjs, jest.config.base.js, jest.config.base.cjs, jest.config.base.mjs, jest.config.common.js, jest.config.common.cjs, jest.config.common.mjs, jest.config.babel.js, jest.config.babel.cjs, jest.config.babel.mjs",
    "jest_snapshot": "js.snap, jsx.snap, ts.snap, tsx.snap",
    "jekyll": "jekyll",
    "jenkins": "jenkins, declarative, jenkinsfile",
    "jinja": "jinja, jinja-html, jinja-xml, jinja-css, jinja-json, jinja-md, jinja-py, jinja-rb, jinja-js, jinja-yaml, jinja-toml, jinja-latex, jinja-lua, jinja-properties, jinja-shell, jinja-dockerfile, jinja-sql, jinja-terraform, jinja-nginx, jinja-groovy, jinja-systemd, jinja-cpp",
    "jpm": ".jpmignore",
    "js": "javascript",
    "js_official": "javascript",
    "jsbeautify": ".jsbeautifyrc, jsbeautifyrc, .jsbeautify, jsbeautify",
    "jsconfig": "jsconfig.json",
    "jscpd": ".jscpd.json, jscpd-report.xml, jscpd-report.json, jscpd-report.html",
    "jshint": ".jshintrc, .jshintignore",
    "jsmap": "js.map, cjs.map, mjs.map",
    "json": "jsonl, ndjson, json, json-tmlanguage, jsonc",
    "json_official": "jsonl, ndjson, json, json-tmlanguage, jsonc",
    "json2": "jsonl, ndjson, json, json-tmlanguage, jsonc",
    "jsonnet": "jsonnet",
    "json5": "json5, json5",
    "jsonld": "jsonld, json-ld",
    "jsp": "jsp",
    "jss": "jss",
    "julia": "julia, juliamarkdown",
    "julia2": "julia, juliamarkdown",
    "jupyter": "ipynb",
    "io": "io",
    "iodine": "iodine",
    "k": "k",
    "karma": "karma.conf.js, karma.conf.coffee, karma.conf.ts",
    "key": "key, pem",
    "kite": ".kiteignore",
    "kitchenci": ".kitchen.yml, kitchen.yml",
    "kivy": "kivy",
    "kos": "kos",
    "kotlin": "kotlin",
    "kusto": "kusto",
    "latino": "latino",
    "layout": "layout.html, layout.htm",
    "lerna": "lerna.json",
    "less": "less",
    "lex": "lex",
    "license": "license, licence, copying, copying.lesser, license-mit, license-apache, license.md, license.txt, licence.md, licence.txt, copying.md, copying.txt, copying.lesser.md, copying.lesser.txt, license-mit.md, license-mit.txt, license-apache.md, license-apache.txt",
    "licensebat": ".licrc",
    "lighthouse": ".lighthouserc.js, .lighthouserc.json, .lighthouserc.yaml, .lighthouserc.yml",
    "lisp": "lisp, autolisp, autolispdcl",
    "lime": "include.xml",
    "lintstagedrc": ".lintstagedrc, .lintstagedrc.json, .lintstagedrc.yaml, .lintstagedrc.yml, .lintstagedrc.mjs, .lintstagedrc.js, .lintstagedrc.cjs, lint-staged.config.mjs, lint-staged.config.js, lint-staged.config.cjs",
    "liquid": "liquid",
    "livescript": "ls",
    "lnk": "lnk",
    "locale": "",
    "log": "log, tlg, log",
    "lolcode": "lolcode",
    "lsl": "lsl",
    "lua": "lua",
    "luau": "luau",
    "lync": "crec, ocrec",
    "makefile": "makefile, makefile",
    "manifest": "manifest",
    "manifest_skip": "manifest.skip",
    "manifest_bak": "manifest.bak",
    "map": "map",
    "markdown": "mdown, markdown, markdown",
    "markdownlint": ".markdownlint.json",
    "markdownlint_ignore": ".markdownlintignore",
    "marko": "marko",
    "markojs": "marko.js",
    "matlab": "fig, mex, mexn, mexrs6, mn, mum, mx, mx3, rwd, slx, slddc, smv, xvc, matlab",
    "maxscript": "maxscript",
    "maven": "maven.config, pom.xml, extensions.xml, settings.xml",
    "maya": "mel",
    "mdx": "mdx",
    "mediawiki": "mediawiki",
    "mercurial": ".hgignore",
    "meson": "meson",
    "meteor": "",
    "mjml": "mjml",
    "mlang": "powerquery",
    "mocha": "mocha.opts, .mocharc.js, .mocharc.json, .mocharc.jsonc, .mocharc.yaml, .mocharc.yml",
    "modernizr": "modernizr, modernizr.js, modernizrrc.js, .modernizr.js, .modernizrrc.js",
    "mojolicious": "mojolicious",
    "moleculer": "moleculer.config.js, moleculer.config.json, moleculer.config.ts",
    "mongo": "mongo",
    "monotone": ".mtn-ignore",
    "mson": "mson",
    "mustache": "mustache, mst",
    "ndst": "ndst.yaml, ndst.yml, ndst.json",
    "nearly": "nearley",
    "nestjs": ".nest-cli.json, nest-cli.json, nestconfig.json, .nestconfig.json",
    "nest_adapter_js": "adapter.js",
    "nest_adapter_ts": "adapter.ts",
    "nest_controller_js": "controller.js",
    "nest_controller_ts": "controller.ts",
    "nest_decorator_js": "decorator.js",
    "nest_decorator_ts": "decorator.ts",
    "nest_filter_js": "filter.js",
    "nest_filter_ts": "filter.ts",
    "nest_gateway_js": "gateway.js",
    "nest_gateway_ts": "gateway.ts",
    "nest_guard_js": "guard.js",
    "nest_guard_ts": "guard.ts",
    "nest_interceptor_js": "interceptor.js",
    "nest_interceptor_ts": "interceptor.ts",
    "nest_middleware_js": "middleware.js",
    "nest_middleware_ts": "middleware.ts",
    "nest_module_js": "module.js",
    "nest_module_ts": "module.ts",
    "nest_pipe_js": "pipe.js",
    "nest_pipe_ts": "pipe.ts",
    "nest_service_js": "service.js",
    "nest_service_ts": "service.ts",
    "netlify": "netlify.toml",
    "next": "next.config.js, next.config.mjs",
    "nginx": "nginx.conf",
    "nim": "nim",
    "nimble": "nimble",
    "ninja": "build.ninja",
    "noc": "noc",
    "nix": "nix",
    "njsproj": "njsproj",
    "node": ".node-version, .nvmrc",
    "node2": ".node-version, .nvmrc",
    "nodemon": "nodemon.json",
    "npm": ".npmignore, .npmrc, package.json, package-lock.json, npm-shrinkwrap.json",
    "nsi": "nsis, nfl, nsl, bridlensis",
    "nsri": ".nsrirc, .nsriignore, nsri.config.js, .nsrirc.js, .nsrirc.json, .nsrirc.yaml, .nsrirc.yml",
    "nsri-integrity": ".integrity.json",
    "nuget": "nupkg, snupkg, nuspec, psmdcp",
    "numpy": "npy, npz",
    "nunjucks": "nunj, njs, nunjucks",
    "nuxt": "nuxt.config.js, nuxt.config.ts",
    "nyc": ".nycrc, .nycrc.json",
    "objectivec": "objective-c",
    "objectivecpp": "objective-cpp",
    "objidconfig": ".objidconfig",
    "ocaml": ".merlin, ocaml, ocamllex, menhir",
    "ogone": "ogone",
    "onenote": "one, onepkg, onetoc, onetoc2, sig",
    "openscad": "scad",
    "opencl": "cl, opencl",
    "openHAB": "openhab",
    "org": "org",
    "outlook": "pst, bcmx, otm, msg, oft",
    "ovpn": "ovpn",
    "package": "pkg",
    "paket": "paket.dependencies, paket.lock, paket.references, paket.template, paket.local",
    "patch": "patch",
    "pcl": "pcd",
    "pddl": "pddl",
    "pddl_plan": "plan",
    "pddl_happenings": "happenings",
    "pdf": "pdf",
    "pdf2": "pdf",
    "peeky": "peeky.config.ts, peeky.config.js, peeky.config.mjs",
    "perl": "perl",
    "perl2": "perl",
    "perl6": "perl6",
    "pgsql": "pgsql",
    "photoshop": "psd",
    "photoshop2": "psd",
    "php": "php1, php2, php3, php4, php5, php6, phps, phpsa, phpt, phtml, phar, php",
    "php2": "php1, php2, php3, php4, php5, php6, phps, phpsa, phpt, phtml, phar, php",
    "php3": "php1, php2, php3, php4, php5, php6, phps, phpsa, phpt, phtml, phar, php",
    "phpcsfixer": ".php_cs, .php_cs.dist",
    "phpunit": "phpunit, phpunit.xml, phpunit.xml.dist",
    "phraseapp": ".phraseapp.yml",
    "pine": "pine, pinescript",
    "pip": "pipfile, pipfile.lock, pip-requirements",
    "pipeline": "pipeline",
    "platformio": "platformio.ini, platformio-debug.disassembly, platformio-debug.memoryview, platformio-debug.asm",
    "plantuml": "pu, plantuml, iuml, puml",
    "playwright": "playwright.config.js, playwright.config.ts",
    "plsql": "plsql, oracle",
    "plsql_package": "pck",
    "plsql_package_body": "pkb",
    "plsql_package_header": "pkh",
    "plsql_package_spec": "pks",
    "pnpm": "pnpmfile.js, pnpm-lock.yaml, pnpm-workspace.yaml",
    "poedit": "po, mo",
    "polymer": "polymer",
    "pony": "pony",
    "postcss": "postcss",
    "postcssconfig": ".postcssrc, .postcssrc.json, .postcssrc.yaml, .postcssrc.yml, .postcssrc.ts, .postcssrc.js, .postcssrc.cjs, postcss.config.ts, postcss.config.js, postcss.config.cjs",
    "powerpoint": "pot, potx, potm, pps, ppsx, ppsm, ppt, pptx, pptm, pa, ppa, ppam, sldm, sldx",
    "powerpoint2": "pot, potx, potm, pps, ppsx, ppsm, ppt, pptx, pptm, pa, ppa, ppam, sldm, sldx",
    "powershell": "powershell",
    "powershell_psm": "psm1",
    "powershell_psd": "psd1",
    "powershell_format": "format.ps1xml",
    "powershell_types": "types.ps1xml",
    "powershell2": "powershell",
    "powershell_psm2": "psm1",
    "powershell_psd2": "psd1",
    "preact": "preact.config.js",
    "precommit": ".pre-commit-config.yaml",
    "prettier": ".prettierrc.js, .prettierrc.cjs, .prettierrc.json, .prettierrc.json5, .prettierrc.yml, .prettierrc.yaml, .prettierrc.toml",
    "prisma": "prisma",
    "processinglang": "pde",
    "procfile": "procfile",
    "progress": "abl",
    "prolog": "pro, P, prolog",
    "prometheus": "prometheus",
    "protobuf": "proto3, proto",
    "protractor": "protractor.conf.js, protractor.conf.coffee, protractor.conf.ts",
    "publisher": "pub, puz",
    "puppet": "puppet",
    "pug": ".jade-lintrc, .pug-lintrc, .jade-lint.json, .pug-lintrc.js, .pug-lintrc.json, jade",
    "purescript": "purescript",
    "pyret": "pyret",
    "python": "python",
    "pytyped": "py.typed",
    "pyup": ".pyup, .pyup.yml",
    "q": "q",
    "qbs": "qbs",
    "qlikview": "qvd, qvw, qlik",
    "qml": "qml",
    "qmldir": "qmldir",
    "qsharp": "qsharp",
    "quasar": "quasar.config.js, quasar.conf.js",
    "r": "r",
    "racket": "racket",
    "rails": "",
    "rake": "rakefile",
    "raml": "raml",
    "razor": "razor, aspnetcorerazor",
    "razzle": "razzle.config.js",
    "reactjs": "javascriptreact",
    "reacttemplate": "rt",
    "reactts": "typescriptreact",
    "reason": "reason",
    "red": "red",
    "registry": "reg",
    "rego": "rego",
    "rehype": ".rehyperc, .rehypeignore, .rehyperc.cjs, .rehyperc.js, .rehyperc.json, .rehyperc.mjs, .rehyperc.yml, .rehyperc.yaml",
    "remark": ".remarkrc, .remarkignore, .remarkrc.cjs, .remarkrc.js, .remarkrc.json, .remarkrc.mjs, .remarkrc.yml, .remarkrc.yaml",
    "renovate": ".renovaterc, renovate.json, .renovaterc.json",
    "replit": ".replit, replit.nix",
    "rescript": "rescript",
    "rest": "restructuredtext",
    "retext": ".retextrc, .retextignore, .retextrc.cjs, .retextrc.js, .retextrc.json, .retextrc.mjs, .retextrc.yml, .retextrc.yaml",
    "rexx": "rexx",
    "riot": "riot",
    "robotframework": "robot",
    "robots": "robots.txt",
    "rollup": "rollup.config.js, rollup.config.cjs, rollup.config.mjs, rollup.config.coffee, rollup.config.ts, rollup.config.common.js, rollup.config.common.cjs, rollup.config.common.mjs, rollup.config.common.coffee, rollup.config.common.ts, rollup.config.dev.js, rollup.config.dev.cjs, rollup.config.dev.mjs, rollup.config.dev.coffee, rollup.config.dev.ts, rollup.config.prod.js, rollup.config.prod.cjs, rollup.config.prod.mjs, rollup.config.prod.coffee, rollup.config.prod.ts",
    "ron": "ron",
    "rmd": "rmd",
    "rproj": "rproj",
    "rspec": ".rspec",
    "rubocop": ".rubocop.yml, .rubocop_todo.yml",
    "ruby": "ruby",
    "rust": "rust",
    "rust_toolchain": "rust-toolchain",
    "sails": ".sailsrc",
    "saltstack": "sls",
    "san": "san",
    "sas": "SAS",
    "sass": "sass",
    "sbt": "sbt",
    "scala": "scala",
    "script": "vbscript",
    "scss": "scssm, scss",
    "scilab": "scilab",
    "sdlang": "sdl",
    "sentry": ".sentryclirc",
    "serverless": "serverless.yml, serverless.json, serverless.js, serverless.ts",
    "sequelize": ".sequelizerc, .sequelizerc.js, .sequelizerc.json",
    "shaderlab": "unity, shaderlab",
    "shell": "fish, shellscript",
    "siyuan": "sy",
    "sketch": "sketch",
    "slang": "slang",
    "slashup": "slash-up.config.js",
    "slice": "slice",
    "slim": "slim",
    "sln": "sln",
    "sln2": "sln",
    "silverstripe": "silverstripe",
    "skipper": "eskip, eskip",
    "smarty": "smarty",
    "snapcraft": "snapcraft.yaml",
    "snort": "snort",
    "snyk": ".snyk",
    "solidarity": ".solidarity, .solidarity.json",
    "solidity": "solidity",
    "source": "",
    "spacengine": "spe",
    "sparql": "sparql",
    "sqf": "sqf",
    "sql": "sql",
    "sqlite": "sqlite, sqlite3, db3",
    "squirrel": "squirrel",
    "sss": "sss",
    "stan": "stan",
    "stata": "dta, stata",
    "stencil": "stencil, stencil-html",
    "stryker": "stryker.conf.mjs, stryker.conf.cjs, stryker.conf.js, stryker.conf.conf, stryker.conf.json, .stryker.conf.mjs, .stryker.conf.cjs, .stryker.conf.js, .stryker.conf.conf, .stryker.conf.json, stryker-config.mjs, stryker-config.cjs, stryker-config.js, stryker-config.conf, stryker-config.json, stryker4s.mjs, stryker4s.cjs, stryker4s.js, stryker4s.conf, stryker4s.json",
    "style": "",
    "stylelint": ".stylelintrc, .stylelintignore, .stylelintcache, stylelint.config.js, stylelint.config.json, stylelint.config.yaml, stylelint.config.yml, stylelint.config.ts, stylelint.config.cjs, .stylelintrc.js, .stylelintrc.json, .stylelintrc.yaml, .stylelintrc.yml, .stylelintrc.ts, .stylelintrc.cjs",
    "stylable": "stylable",
    "styled": "source.css.styled",
    "stylish_haskell": ".stylish-haskell.yaml",
    "stylus": "stylus",
    "storyboard": "storyboard",
    "storybook": "story.js, story.jsx, story.ts, story.tsx, story.mdx, stories.js, stories.jsx, stories.ts, stories.tsx, stories.mdx",
    "subversion": ".svnignore",
    "svelte": "svelte",
    "svg": "svg",
    "swagger": "Swagger, swagger",
    "swift": "package.pins, swift",
    "swig": "swig",
    "symfony": "symfony.lock",
    "systemd": "systemd-unit-file",
    "systemverilog": "systemverilog",
    "t4tt": "t4",
    "tailwind": "tailwind.js, tailwind.cjs, tailwind.coffee, tailwind.ts, tailwind.json, tailwind.config.js, tailwind.config.cjs, tailwind.config.coffee, tailwind.config.ts, tailwind.config.json, .tailwind.js, .tailwind.cjs, .tailwind.coffee, .tailwind.ts, .tailwind.json, .tailwindrc.js, .tailwindrc.cjs, .tailwindrc.coffee, .tailwindrc.ts, .tailwindrc.json",
    "tauri": "tauri.conf.json",
    "teal": "teal",
    "tt": "tt2, tt",
    "tcl": "tcl, exp",
    "tera": "tera",
    "terraform": "tfstate, terraform",
    "test": "tst",
    "testcafe": ".testcaferc.json",
    "testjs": "test.js, test.jsx, test.mjs, spec.js, spec.jsx, spec.mjs",
    "testts": "test.ts, test.tsx, spec.ts, spec.tsx, e2e-test.ts, e2e-test.tsx, e2e-spec.ts, e2e-spec.tsx",
    "tex": "texi, tikz, tex, latex, bibtex, doctex",
    "text": "csv, tsv, plaintext",
    "textile": "textile",
    "tiltfile": "tiltfile",
    "tfs": ".tfignore",
    "todo": "todo",
    "toit": "toit",
    "toml": "toml",
    "tox": "tox.ini",
    "travis": ".travis.yml",
    "trunk": "trunk.yaml",
    "tsconfig": "tsconfig.json, tsconfig.app.json, tsconfig.base.json, tsconfig.common.json, tsconfig.dev.json, tsconfig.development.json, tsconfig.e2e.json, tsconfig.eslint.json, tsconfig.node.json, tsconfig.prod.json, tsconfig.production.json, tsconfig.server.json, tsconfig.spec.json, tsconfig.staging.json, tsconfig.test.json, tsconfig.lib.json, tsconfig.lib.prod.json",
    "tsconfig_official": "tsconfig.json, tsconfig.app.json, tsconfig.base.json, tsconfig.common.json, tsconfig.dev.json, tsconfig.development.json, tsconfig.e2e.json, tsconfig.node.json, tsconfig.prod.json, tsconfig.production.json, tsconfig.server.json, tsconfig.spec.json, tsconfig.staging.json, tsconfig.test.json, tsconfig.lib.json, tsconfig.lib.prod.json",
    "tslint": "tslint.json, tslint.yaml, tslint.yml",
    "ttcn": "ttcn",
    "tuc": "tuc",
    "twig": "twig",
    "typedoc": "typedoc.js, typedoc.json",
    "typescript": "typescript",
    "typescript_official": "typescript",
    "typescriptdef": "d.ts, d.cts, d.mts",
    "typescriptdef_official": "d.ts, d.cts, d.mts",
    "typo3": "typoscript",
    "unibeautify": ".unibeautifyrc, unibeautify.config.js, .unibeautifyrc.js, .unibeautifyrc.json, .unibeautifyrc.yaml, .unibeautifyrc.yml",
    "unlicense": "unlicense, unlicence, unlicense.md, unlicense.txt, unlicence.md, unlicence.txt",
    "vagrant": "vagrantfile",
    "vala": "vala",
    "vanilla_extract": "css.ts",
    "vapi": "vapi",
    "vash": "vash",
    "vapor": "vapor.yml",
    "vb": "vb",
    "vba": "vba",
    "vbhtml": "vbhtml",
    "vbproj": "vbproj",
    "vcxproj": "vcxproj",
    "velocity": "velocity",
    "verilog": "verilog",
    "vhdl": "vhdl",
    "video": "3g2, 3gp, asf, amv, avi, divx, qt, f4a, f4b, f4p, f4v, flv, m2v, m4v, mkv, mk3d, mov, mp2, mp4, mpe, mpeg, mpeg2, mpg, mpv, nsv, ogv, rm, rmvb, svi, vob, webm, wmv",
    "view": "",
    "vim": ".vimrc, .gvimrc, viml",
    "vite": "vite.config.js, vite.config.ts",
    "vitest": "vitest.config.ts, vitest.config.js, vitest.config.mjs",
    "vlang": "v",
    "volt": "volt",
    "vscode": ".vscodeignore, launch.json, tasks.json, vscodeignore.json",
    "vscode2": ".vscodeignore, launch.json, tasks.json, vscodeignore.json",
    "vscode3": ".vscodeignore, launch.json, tasks.json, vscodeignore.json",
    "vscode-insiders": ".vscodeignore, launch.json, tasks.json, vscodeignore.json",
    "vsix": "vsix",
    "vsixmanifest": "vsixmanifest",
    "vue": "vue",
    "vueconfig": ".vuerc, vue.config.js, vue.config.cjs, vue.config.mjs",
    "wallaby": "wallaby.json, wallaby.js, wallaby.ts, wallaby.coffee, wallaby.conf.json, wallaby.conf.js, wallaby.conf.ts, wallaby.conf.coffee, .wallaby.json, .wallaby.js, .wallaby.ts, .wallaby.coffee, .wallaby.conf.json, .wallaby.conf.js, .wallaby.conf.ts, .wallaby.conf.coffee",
    "watchmanconfig": ".watchmanconfig",
    "wasm": "wasm, wasm, wat",
    "webpack": "webpack.base.conf.js, webpack.base.conf.coffee, webpack.base.conf.ts, webpack.common.js, webpack.common.coffee, webpack.common.ts, webpack.config.js, webpack.config.coffee, webpack.config.ts, webpack.config.base.js, webpack.config.base.coffee, webpack.config.base.ts, webpack.config.common.js, webpack.config.common.coffee, webpack.config.common.ts, webpack.config.dev.js, webpack.config.dev.coffee, webpack.config.dev.ts, webpack.config.development.js, webpack.config.development.coffee, webpack.config.development.ts, webpack.config.staging.js, webpack.config.staging.coffee, webpack.config.staging.ts, webpack.config.test.js, webpack.config.test.coffee, webpack.config.test.ts, webpack.config.prod.js, webpack.config.prod.coffee, webpack.config.prod.ts, webpack.config.production.js, webpack.config.production.coffee, webpack.config.production.ts, webpack.config.babel.js, webpack.config.babel.coffee, webpack.config.babel.ts, webpack.config.base.babel.js, webpack.config.base.babel.coffee, webpack.config.base.babel.ts, webpack.config.common.babel.js, webpack.config.common.babel.coffee, webpack.config.common.babel.ts, webpack.config.dev.babel.js, webpack.config.dev.babel.coffee, webpack.config.dev.babel.ts, webpack.config.development.babel.js, webpack.config.development.babel.coffee, webpack.config.development.babel.ts, webpack.config.staging.babel.js, webpack.config.staging.babel.coffee, webpack.config.staging.babel.ts, webpack.config.test.babel.js, webpack.config.test.babel.coffee, webpack.config.test.babel.ts, webpack.config.prod.babel.js, webpack.config.prod.babel.coffee, webpack.config.prod.babel.ts, webpack.config.production.babel.js, webpack.config.production.babel.coffee, webpack.config.production.babel.ts, webpack.dev.js, webpack.dev.coffee, webpack.dev.ts, webpack.dev.conf.js, webpack.dev.conf.coffee, webpack.dev.conf.ts, webpack.prod.js, webpack.prod.coffee, webpack.prod.ts, webpack.prod.conf.js, webpack.prod.conf.coffee, webpack.prod.conf.ts, webpack.main.config.js, webpack.main.config.coffee, webpack.main.config.ts, webpack.mix.js, webpack.mix.coffee, webpack.mix.ts, webpack.plugins.js, webpack.plugins.coffee, webpack.plugins.ts, webpack.renderer.config.js, webpack.renderer.config.coffee, webpack.renderer.config.ts, webpack.rules.js, webpack.rules.coffee, webpack.rules.ts, webpack.test.conf.js, webpack.test.conf.coffee, webpack.test.conf.ts",
    "wenyan": "wenyan",
    "wercker": "wercker.yml",
    "windi": "windi.config.ts, windi.config.js",
    "wolfram": "wolfram",
    "word": "doc, docx, docm, dot, dotx, dotm, wll",
    "word2": "doc, docx, docm, dot, dotx, dotm, wll",
    "wpml": "wpml-config.xml",
    "wurst": "wurstlang, wurst",
    "wxml": "wxml",
    "wxss": "wxss",
    "xcode": "xcodeproj",
    "xfl": "xfl",
    "xib": "xib",
    "xliff": "xliff, xlf",
    "xmake": "xmake",
    "xml": "pex, tmlanguage, xml",
    "xquery": "xquery",
    "xsl": "xsl",
    "yacc": "yacc",
    "yaml": "yaml, yaml-tmlanguage",
    "yamllint": ".yamllint",
    "yandex": ".yaspellerrc, .yaspeller.json",
    "yang": "yang",
    "yarn": "yarn.lock, .yarnrc, .yarnrc.yml, .yarnclean, .yarn-integrity, .yarn-metadata.json, .yarnignore",
    "yeoman": ".yo-rc.json",
    "zeit": "now.json, .nowignore, vercel.json, .vercelignore",
    "zig": "zig",
    "turbo": "turbo.json",
    "doppler": "doppler.yaml, doppler-template.yaml",
    "zip": "zip, rar, 7z, tar, tgz, bz, gz, bzip2, xz, bz2, zipx",
    "zip2": "zip, rar, 7z, tar, tgz, bz, gz, bzip2, xz, bz2, zipx"
}

export const getFileIcon = (extension: string) => {
    let icon: string | null = null;

    if (extension in FileIconTypes) {
        icon = extension;
    } else {

        Object.entries(FileIconTypes).forEach((key) => {
            if (key[1].includes(extension)) {
                icon = key[0];
            }
        })

        if (!icon) {
            icon = "file";
        }
    }

    console.log(baseIconUrl + icon + ".svg");
    

    return baseIconUrl + icon + ".svg";
}